#!/usr/bin/env python3
"""Lint RIS files generated by the Zotero/PubMed evidence skills.

The linter is intentionally lightweight: it validates record boundaries, common
RIS tags, Markdown contamination, unresolved placeholders, and missing fields
that commonly break EndNote import or reference-update workflows.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
COMMON_RIS_TAGS = {
    "TY", "A1", "A2", "A3", "A4", "AB", "AD", "AN", "AU", "BT", "C1", "C2", "C3", "C4",
    "C5", "C6", "C7", "C8", "CA", "CN", "CP", "CT", "CY", "DA", "DB", "DO", "DP", "ED",
    "EP", "ER", "ET", "ID", "IS", "J1", "J2", "JA", "JF", "JO", "KW", "L1", "L2", "L3",
    "L4", "LA", "LB", "M1", "M2", "M3", "N1", "N2", "NV", "OP", "PB", "PM", "PP", "PY", "RI",
    "RN", "RP", "SE", "SN", "SP", "ST", "T1", "T2", "T3", "TA", "TI", "TT", "U1", "U2",
    "U3", "U4", "U5", "UR", "VL", "Y1", "Y2",
}
PLACEHOLDER_RE = re.compile(r"\{(?:PMID|DOI|Title|Journal|Year|Authors?|Zotero key|KEY|URL)[^}]*\}", re.IGNORECASE)
RIS_FIELD_RE = re.compile(r"^([A-Z0-9]{2})  -\s?(.*)$")


@dataclass
class LintMessage:
    path: Path
    severity: str
    message: str
    record: int | None = None

    def format(self) -> str:
        record = f" record {self.record}:" if self.record is not None else ":"
        return f"{self.severity}: {self.path.relative_to(REPO_ROOT) if self.path.is_absolute() and self.path.is_relative_to(REPO_ROOT) else self.path}{record} {self.message}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Lint RIS files or directories; read-only")
    parser.add_argument("paths", nargs="*", default=["zotero-evidence-output", "pubmed-literature-output"], help="RIS file(s) or directories to scan")
    parser.add_argument("--fail-on-warnings", action="store_true", help="Exit non-zero on warnings as well as errors")
    parser.add_argument("--ignore-before", metavar="YYYY-MM-DD", help="Suppress warnings for RIS files in packages dated before this cutoff")
    return parser.parse_args()


def parse_cutoff(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise SystemExit(f"Invalid --ignore-before date {value!r}; expected YYYY-MM-DD") from exc


def extract_path_date(path: Path) -> date | None:
    for part in reversed(path.parts):
        match = re.search(r"(20\d{2}-\d{2}-\d{2})", part)
        if not match:
            continue
        try:
            return date.fromisoformat(match.group(1))
        except ValueError:
            continue
    return None


def is_historical_warning(message: LintMessage, cutoff: date | None) -> bool:
    if message.severity != "WARNING" or not cutoff:
        return False
    path_day = extract_path_date(message.path)
    return bool(path_day and path_day < cutoff)


def resolve_path(path_text: str) -> Path:
    path = Path(path_text)
    return path if path.is_absolute() else REPO_ROOT / path

def discover_ris_files(paths: list[str]) -> list[Path]:
    files: list[Path] = []
    for path_text in paths:
        path = resolve_path(path_text)
        if not path.exists():
            continue
        if path.is_file() and path.suffix.lower() == ".ris":
            files.append(path)
        elif path.is_dir():
            files.extend(sorted(path.rglob("*.ris")))
    return sorted(set(files))


def split_records(text: str) -> tuple[list[list[str]], list[str]]:
    records: list[list[str]] = []
    current: list[str] = []
    preamble: list[str] = []
    for line in text.splitlines():
        if line.startswith("TY  -"):
            if current:
                records.append(current)
            current = [line]
            continue
        if current:
            current.append(line)
            if line.startswith("ER  -"):
                records.append(current)
                current = []
        elif line.strip():
            preamble.append(line)
    if current:
        records.append(current)
    return records, preamble


def fields_for(record: list[str]) -> dict[str, list[str]]:
    fields: dict[str, list[str]] = {}
    for line in record:
        if not line.strip():
            continue
        match = RIS_FIELD_RE.match(line)
        if match:
            fields.setdefault(match.group(1), []).append(match.group(2).strip())
    return fields


def lint_text(path: Path, text: str) -> list[LintMessage]:
    messages: list[LintMessage] = []
    if re.search(r"^#{1,6}\s", text, flags=re.MULTILINE):
        messages.append(LintMessage(path, "ERROR", "contains Markdown heading"))
    if "```" in text:
        messages.append(LintMessage(path, "ERROR", "contains Markdown code fence"))
    if re.search(r"^[-*]\s+", text, flags=re.MULTILINE):
        messages.append(LintMessage(path, "ERROR", "contains Markdown bullet/prose line"))
    if PLACEHOLDER_RE.search(text):
        messages.append(LintMessage(path, "ERROR", "contains unresolved placeholder such as {PMID}, {DOI}, or {Title}"))

    records, preamble = split_records(text)
    if preamble:
        messages.append(LintMessage(path, "ERROR", "contains non-RIS preamble before first TY record"))
    if not records:
        messages.append(LintMessage(path, "ERROR", "contains no RIS records"))
        return messages

    for index, record in enumerate(records, start=1):
        first = next((line for line in record if line.strip()), "")
        last = next((line for line in reversed(record) if line.strip()), "")
        if not first.startswith("TY  -"):
            messages.append(LintMessage(path, "ERROR", "record does not start with TY  -", index))
        if not last.startswith("ER  -"):
            messages.append(LintMessage(path, "ERROR", "record does not end with ER  -", index))

        for line in record:
            if not line.strip():
                continue
            match = RIS_FIELD_RE.match(line)
            if not match:
                messages.append(LintMessage(path, "ERROR", f"non-RIS line: {line[:80]}", index))
                continue
            tag = match.group(1)
            if tag not in COMMON_RIS_TAGS:
                messages.append(LintMessage(path, "WARNING", f"uncommon RIS tag `{tag}`", index))

        fields = fields_for(record)
        item_type = fields.get("TY", [""])[0]
        if not any(tag in fields for tag in ("TI", "T1", "CT")):
            messages.append(LintMessage(path, "WARNING", "missing title field (TI/T1/CT)", index))
        if not any(tag in fields for tag in ("AU", "A1")):
            messages.append(LintMessage(path, "WARNING", "missing author field (AU/A1)", index))
        if not any(tag in fields for tag in ("PY", "Y1", "DA")):
            messages.append(LintMessage(path, "WARNING", "missing publication year/date field (PY/Y1/DA)", index))
        if item_type == "JOUR" and not any(tag in fields for tag in ("JO", "JF", "JA", "T2")):
            messages.append(LintMessage(path, "WARNING", "journal article missing journal title field (JO/JF/JA/T2)", index))
        if not any(tag in fields for tag in ("DO", "UR", "SN", "N1")):
            messages.append(LintMessage(path, "WARNING", "missing stable identifier or note (DO/UR/SN/N1)", index))
    return messages


def lint_file(path: Path) -> list[LintMessage]:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return [LintMessage(path, "ERROR", "is not valid UTF-8")]
    return lint_text(path, text)


def main() -> None:
    args = parse_args()
    files = discover_ris_files(args.paths)
    if not files:
        print("No RIS files found.")
        return

    all_messages: list[LintMessage] = []
    for path in files:
        all_messages.extend(lint_file(path))

    print(f"Scanned RIS files: {len(files)}")
    cutoff = parse_cutoff(args.ignore_before)
    errors = [message for message in all_messages if message.severity == "ERROR"]
    warnings = [message for message in all_messages if message.severity == "WARNING"]
    active_warnings = [message for message in warnings if not is_historical_warning(message, cutoff)]
    suppressed_count = len(warnings) - len(active_warnings)
    if all_messages:
        for message in all_messages:
            print(message.format())
    else:
        print("No RIS lint warnings detected.")
    if cutoff:
        print(f"Historical warning cutoff: suppressing {suppressed_count} warning(s) from RIS files before {cutoff.isoformat()}.")

    if errors or (args.fail_on_warnings and active_warnings):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
